- name:  "Ansible 2.14+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.14', '>=')
    msg: "Required Ansible version is 7 with 2.14+ (core)"

- name: "Debian 10/11 required"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in [ "10", "11" ]
    msg: "Only Debian 10/11 is supported, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: "compute base DN"
  set_fact:
    ldap_basedn: '{{ "dc=" + ldap_domain.split(".") | join(",dc=") }}'

- name: "compute data admin DN"
  set_fact:
    ldap_data_admin_dn: '{{ "cn=admin," + ldap_basedn }}'

- name: "backports repo"
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    filename: "{{ ansible_distribution_release }}-backports"
    update_cache: yes

# available debconf options for slapd are in https://salsa.debian.org/openldap-team/openldap/-/blob/master/debian/slapd.templates
- name: "configure domain for OpenLDAP using debconf"
  debconf:
    name: slapd
    question: slapd/domain
    vtype: string
    value: '{{ ldap_domain }}'

- name: "configure attribute o for top entry using debconf"
  debconf:
    name: slapd
    question: shared/organization
    vtype: string
    value: "{{ ldap_top_organization }}"

- name: "configure purging OpenLDAP database when uninstalling using debconf"
  debconf:
    name: slapd
    question: slapd/purge_database
    vtype: boolean
    value: 'true'

- name: "configure data admin password for OpenLDAP using debconf"
  debconf:
    name: slapd
    question: "{{ item }}"
    vtype: password
    value: "{{ ldap_data_password }}"
  # wrongly reports as changed even when not changed, see https://github.com/ansible/ansible/issues/47676
  changed_when: False
  no_log: True
  loop:
    - slapd/password1
    - slapd/password2

- name: "install software packages"
  apt:
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
    name:
      - slapd
      - ldap-utils
      - python3-ldap

# libldap-common is a dependency for python-apt so it is already installed in older version
# and thus not upgraded by the previous step
- name: "update libldap-common to latest version"
  apt:
    state: latest
    default_release: "{{ ansible_distribution_release }}-backports"
    name: libldap-common

- name: "make sure the /etc/ldap/ldap.conf file exists (it is part of package libldap-common)"
  template:
    backup: true
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: '0644'

- name: "get package facts"
  package_facts:
    manager: "apt"
- name: "detect slapd package version"
  set_fact:
    slapd_24: >-
      {{ ansible_facts.packages['slapd'][0].version is version('2.4', '>=')
      and ansible_facts.packages['slapd'][0].version is version('2.5', '<') }}
- name: "decide argon2 module name (different in 2.4 and 2.5 versions)"
  set_fact:
    argon2_module_name: "{{ 'pw-argon2' if slapd_24 else 'argon2' }}"
    default_hash: "{{ '{ARGON2}' if ldap_strong_password_hashing else '{SHA}' }}"
- name: "decide parameters for slappasswd"
  set_fact:
    slappasswd_argv: >
      {{ [ 'slappasswd', '-h', default_hash ] +
         ( [ '-o', 'module-load=/usr/lib/ldap/'+argon2_module_name+'.so' ] if  ldap_strong_password_hashing else [] )
      }}
- debug:
    msg: >-
      slapd version: {{ ansible_facts.packages['slapd'][0].version }}
      slapd_24: {{ slapd_24 }}
      argon2 module: {{ argon2_module_name }}
      slappasswd_argv: {{ slappasswd_argv }}

- name: "install slapd-contrib with Argon2 key derivation function"
  when: ldap_strong_password_hashing and slapd_24
  apt:
    default_release: "{{ ansible_distribution_release }}-backports"
    name: slapd-contrib
    state: present

- name: "hold slapd package from upgrading"
  when: ldap_hold_package
  dpkg_selections:
    name: slapd
    selection: hold

- name: "compute config admin password hash (not idempotent for salted hashes)"
  command:
    argv: "{{ slappasswd_argv + [ '-s', ldap_config_password ] }}"
  register: ldap_config_admin_password_hash
  changed_when: False
  no_log: True

- name: "set config admin password"
  ldap_attrs:
    dn: olcDatabase={0}config,cn=config
    attributes:
      olcRootPW: "{{ ldap_config_admin_password_hash.stdout }}"
    state: exact
  no_log: True

- name: "compute data admin password hash (not idempotent for salted hashes)"
  when: ldap_strong_password_hashing
  command:
    argv: "{{ slappasswd_argv + [ '-s', ldap_data_password ] }}"
  register: ldap_data_admin_password_hash
  changed_when: False
  no_log: True

- name: "set data admin password"
  when: ldap_strong_password_hashing
  ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcRootPW: "{{ ldap_data_admin_password_hash.stdout }}"
    state: exact
  no_log: True

- name: "add openldap user to ssl-cert group"
  user:
    name: openldap
    groups: ssl-cert
    append: yes
  register: openldap_ssl_cert_group

- name: "restart OpenLDAP after openldap user added to group ssl-cert"
  service:
    name: slapd
    state: restarted
  when: openldap_ssl_cert_group.changed

- name: "modify LDAP TLS settings"
  ldap_attrs:
    dn: cn=config
    attributes:
      olcTLSCertificateFile: "{{ ldap_certificate_file }}"
      olcTLSCertificateKeyFile: "{{ ldap_certificate_key_file }}"
      olcTLSCACertificateFile: "{{ ldap_certificate_chain_file }}"
    state: exact
  register: ssl_ldif

- name: "enable secure port, plain ldap and local connection"
  lineinfile:
    dest: /etc/default/slapd
    regexp: ^SLAPD_SERVICES=
    line: SLAPD_SERVICES="ldaps:/// ldapi:/// ldap:///"
  register: secure_port_enabled

- name: "restart OpenLDAP after enabling TLS"
  service:
    name: slapd
    state: restarted
  when: secure_port_enabled.changed or ssl_ldif.changed

- name: "set olcDbMaxSize on olcDatabase={1}mdb"
  ldap_attrs:
    dn: "olcDatabase={1}mdb,cn=config"
    attributes:
      olcDbMaxSize: "{{ ldap_mdb1_olcDbMaxSize }}"
    state: exact

- name: "size in MiB"
  debug:
    msg: "olcDbMaxSize is {{ ldap_mdb1_olcDbMaxSize / (1024 * 1024) }} MiB"

- name: "pass-through authentication"
  when: ldap_pass_through_authentication
  block:
    - name: "install kerberos and sasl"
      apt:
        name:
          - krb5-user
          - sasl2-bin
        state: present
    - name: "krb5.conf"
      get_url:
        url: https://metavo.metacentrum.cz/krb5.conf
        dest: /etc/krb5.conf
        force: yes
    - name: "saslauthd START=yes"
      lineinfile:
        path: /etc/default/saslauthd
        regexp: 'START='
        line: 'START=yes'
    - name: "saslauthd MECHANISMS=kerberos5"
      lineinfile:
        path: /etc/default/saslauthd
        regexp: 'MECHANISMS='
        line: 'MECHANISMS="kerberos5"'
    - name: "start saslauthd"
      service:
        name: saslauthd
        state: started
    - name: "sasl2 config"
      copy:
        dest: /usr/lib/sasl2/slapd.conf
        content: |
          pwcheck_method: saslauthd
          mech_list: plain login external
      register: sasl_first_pass
    - name: "add user openldap to group sasl"
      user:
        name: openldap
        groups: sasl
        append: yes
    - name: "restart OpenLDAP after enabling SASL"
      service:
        name: slapd
        state: restarted
      when: sasl_first_pass.changed

- name: "OpenLDAP modules"
  block:
    - name: "modules lists"
      set_fact:
        olcModuleLoad_values: [ 'back_mdb' ]
    - name: "modules for master replica"
      when: ldap_master_replica
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  [ 'syncprov', 'accesslog' ] }}"
    - name: "modules for memberOf overlay"
      when: ldap_memberOf_overlay
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  [ 'memberof', 'refint' ] }}"
    - name: "module for sssvlv overlay"
      when: ldap_sssvlv_overlay
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  [ 'sssvlv' ] }}"
    - name: "module argon2"
      when: ldap_strong_password_hashing
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  [ argon2_module_name ] }}"
    - name: "activate modules {{ olcModuleLoad_values }}"
      ldap_attrs:
        dn: cn=module{0},cn=config
        attributes:
          olcModuleLoad: "{{ olcModuleLoad_values }}"
        ordered: yes
        state: present

- name: "set strong hashing method as default for password hashing"
  when: ldap_strong_password_hashing
  ldap_attrs:
    dn: "olcDatabase={-1}frontend,cn=config"
    attributes:
      olcPasswordHash: "{ARGON2}"
    state: exact

- name: "create users"
  include_tasks: user_entry.yml
  loop: "{{ ldap_users }}"
  loop_control:
    loop_var: user_entry

- name: "create replica user"
  when: ldap_master_replica
  include_tasks: user_entry.yml
  vars:
    user_entry:
      user: 'replication'
      password: "{{ ldap_replication_password }}"
      description: "user for LDAP replication"

- name: "LDAP access rules"
  when: ldap_access_rules_set
  block:
    - name: "LDAP access rules empty"
      set_fact:
        olcAccess_values: []
        oldAccess_replication:
          - >-
            to dn.subtree="{{ ldap_basedn }}"
            by dn.exact="cn=replication,{{ ldap_basedn }}" read
            by * break
    - name: "LDAP access rule for replication must be first"
      when: ldap_master_replica
      set_fact:
        olcAccess_values: "{{ olcAccess_values + oldAccess_replication }}"
    - name: "LDAP access rules start"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + ldap_access_rules_start }}"
    - name: "additional LDAP access rules"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + ldap_access_rules_additional }}"
    - name: "LDAP access rules end"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + ldap_access_rules_end }}"
    - name: "modify OpenLDAP access rights"
      ldap_attrs:
        dn: olcDatabase={1}mdb,cn=config
        attributes:
          olcAccess: "{{ olcAccess_values }}"
        ordered: yes
        state: exact

- name: "set unlimited size of searches"
  ldap_attrs:
    dn: olcDatabase={-1}frontend,cn=config
    attributes:
      olcSizeLimit: "{{ ldap_size_limit }}"
    state: exact

- name: "master replica"
  when: ldap_master_replica
  block:
    - name: "no limits for replica"
      ldap_attrs:
        dn: olcDatabase={1}mdb,cn=config
        attributes:
          olcLimits:
            - 'dn.exact="cn=replication,{{ ldap_basedn }}" time=unlimited size=unlimited'
        ordered: yes
        state: exact

    - name: "directory for accesslog"
      file:
        path: /var/lib/ldap/accesslog
        state: directory
        owner: openldap
        group: openldap
        mode: '0700'

    # workaround for https://github.com/ansible-collections/community.general/issues/6045
    - name: "detect accesslog database entry"
      community.general.ldap_search:
        dn: "olcDatabase={2}mdb,cn=config"
        scope: base
      register: acclog
      ignore_errors: yes
    - name: "create LDIF for accesslog database"
      when: acclog.failed
      copy:
        dest: /etc/ldap/accesslogdb.ldif
        content: |
          dn: olcDatabase={2}mdb,cn=config
          changetype: add
          objectClass: olcDatabaseConfig
          objectClass: olcMdbConfig
          olcDatabase: {2}mdb
          olcDbDirectory: /var/lib/ldap/accesslog
          olcSuffix: cn=accesslog
          olcAccess: {0}to dn.subtree="cn=accesslog" by dn.exact="cn=replication,{{ ldap_basedn }}" read
          olcLastMod: TRUE
          olcLimits: {0}dn.exact="cn=replication,{{ ldap_basedn }}" time=unlimited size=unlimited
          olcMaxDerefDepth: 15
          olcReadOnly: FALSE
          olcSizeLimit: unlimited
          olcTimeLimit: unlimited
          olcMonitoring: TRUE
          olcDbCheckpoint: 0 0
          olcDbIndex: entryCSN eq
          olcDbIndex: objectClass eq
          olcDbIndex: reqEnd eq
          olcDbIndex: reqResult eq
          olcDbIndex: reqStart eq
          olcDbIndex: reqDN eq
          olcDbMaxSize: 85899345920
          olcDbMode: 0600
          olcDbSearchStack: 16
    - name: "create accesslog database using ldapadd"
      when: acclog.failed
      command: "/usr/bin/ldapadd -Q -H ldapi:/// -Y EXTERNAL -f /etc/ldap/accesslogdb.ldif"

    - name: "accesslog overlay for main database"
      ldap_entry:
        dn: "olcOverlay=accesslog,olcDatabase={1}mdb,cn=config"
        objectClass:
          - olcAccessLogConfig
        attributes:
          olcOverlay: 'accesslog'
          olcAccessLogDb: cn=accesslog
          olcAccessLogOps: writes
          olcAccessLogSuccess: 'TRUE'
          olcAccessLogPurge: '2+00:00 1+00:00'
        state: present

    - name: "syncprov overlay for main database"
      ldap_entry:
        dn: "olcOverlay=syncprov,olcDatabase={1}mdb,cn=config"
        objectClass:
          - olcSyncProvConfig
        attributes:
          olcOverlay: 'syncprov'
          olcSpCheckpoint: '100 10'
        state: present

    - name: "syncprov overlay for accesslog database"
      ldap_entry:
        dn: "olcOverlay=syncprov,olcDatabase={2}mdb,cn=config"
        objectClass:
          - olcSyncProvConfig
        attributes:
          olcOverlay: 'syncprov'
          olcSpCheckpoint: '100 10'
          olcSpNoPresent: 'TRUE'
          olcSpReloadHint: 'TRUE'
        state: present

    - name: "syncprov overlay for config database"
      ldap_entry:
        dn: "olcOverlay=syncprov,olcDatabase={0}config,cn=config"
        objectClass:
          - olcSyncProvConfig
        attributes:
          olcOverlay: 'syncprov'
        state: present

    - name: "modify ACL for config db to allow replication to read schemas"
      ldap_attrs:
        dn: olcDatabase={0}config,cn=config
        attributes:
          olcAccess: >-
            {0}to dn.subtree="cn=schema,cn=config" 
            by dn.exact="cn=replication,{{ ldap_basedn }}" read
            by * break
        state: present

- name: "create ou=People branch"
  when: not ldap_slave_replica
  ldap_entry:
    dn: "ou=People,{{ ldap_basedn }}"
    objectClass: organizationalUnit
    state: present
    bind_dn: "{{ ldap_data_admin_dn }}"
    bind_pw: "{{ ldap_data_password }}"

# overlays need to have index in their names, but the index depend on their number
- name: "memberOf overlay"
  when: ldap_memberOf_overlay
  ldap_entry:
    dn: "olcOverlay=memberof,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - olcMemberOf
      - top
    attributes:
      olcMemberOfRefInt: "TRUE"
    state: present

- name: "refint overlay"
  when: ldap_memberOf_overlay
  ldap_entry:
    dn: "olcOverlay=refint,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - olcRefintConfig
      - top
    attributes:
      olcRefintAttribute: "memberof member manager owner"
    state: present

- name: "sssvlv overlay"
  when: ldap_sssvlv_overlay
  ldap_entry:
    dn: "olcOverlay=sssvlv,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - top
    state: present

- name: "change the standard schema to allow empty groups"
  when: ldap_allow_empty_groups
  tags: hack
  block:
    - name: "copy core.ldif"
      copy:
        src: etc/ldap/schema/core.ldif
        dest: /etc/ldap/schema/core.ldif
      register: f1
    - name: "copy core.schema"
      copy:
        src: etc/ldap/schema/core.schema
        dest: /etc/ldap/schema/core.schema
      register: f2
    - name: "copy cn={0}core.ldif"
      copy:
        src: 'etc/ldap/slapd.d/cn=config/cn=schema/cn={0}core.ldif'
        dest: '/etc/ldap/slapd.d/cn=config/cn=schema/cn={0}core.ldif'
      register: f3
    - name: "restart slapd"
      when: f1.changed or f2.changed or f3.changed
      service:
        name: slapd
        state: restarted

- name: "slave replica"
  when: ldap_slave_replica
  block:
    # see https://www.openldap.org/doc/admin25/slapdconf2.html#olcSyncrepl for replication parameters
    - name: "data replication"
      ldap_attrs:
        dn: "olcDatabase={1}mdb,cn=config"
        attributes:
          olcSyncrepl: >-
            rid=001
            provider={{ ldap_master_url }}
            type=refreshAndPersist
            retry="5 5 300 +"
            searchbase="{{ ldap_basedn }}"
            schemachecking=off
            bindmethod=simple
            binddn="cn=replication,{{ ldap_basedn }}"
            credentials={{ ldap_replication_password }}
            tls_cacert=/etc/ssl/certs/ca-certificates.crt
            logbase="cn=accesslog"
            logfilter="(&(objectClass=auditWriteObject)(reqResult=0))"
            syncdata=accesslog
          olcUpdateRef: "{{ ldap_master_url }}"
        ordered: yes
        state: exact

    - name: "check existence of schema replication"
      community.general.ldap_search:
        dn: "olcDatabase={0}config,cn=config"
        scope: base
      register: configdb
    - name: "set schema replication"
      when: "'olcSyncrepl' not in configdb.results[0]"
      block:
        - name: "create LDIF for setting schema replication"
          copy:
            dest: /etc/ldap/schema_sync.ldif
            content: |
              dn: olcDatabase={0}config,cn=config
              changetype: modify
              add: olcSyncrepl
              olcSyncrepl: rid=002 provider={{ ldap_master_url }} type=refreshAndPersist retry="5 5 300 +" searchbase="cn=schema,cn=config" bindmethod=simple binddn="cn=replication,{{ ldap_basedn }}" credentials=test tls_cacert=/etc/ssl/certs/ca-certificates.crt
              -
              add: olcMultiprovider
              olcMultiprovider: TRUE
        - name: "load LDIF for setting schema replication"
          command: "/usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f /etc/ldap/schema_sync.ldif"
