- name:  "Ansible 2.11+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.11', '>=')
    msg: "Required Ansible version is 4 with 2.11+ (core)"

- name: "Debian 10 required"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in [ "10" ]
    msg: "Only Debian 10 is supported, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: "compute base DN"
  set_fact:
    ldap_basedn: '{{ "dc=" + ldap_domain.split(".") | join(",dc=") }}'

- name: "compute data admin DN"
  set_fact:
    ldap_data_admin_dn: '{{ "cn=admin," + ldap_basedn }}'

- name: "backports repo"
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    filename: "{{ ansible_distribution_release }}-backports"
    update_cache: yes

# available debconf options for slapd are in https://salsa.debian.org/openldap-team/openldap/-/blob/master/debian/slapd.templates
- name: "configure domain for OpenLDAP using debconf"
  debconf:
    name: slapd
    question: slapd/domain
    vtype: string
    value: '{{ ldap_domain }}'

- name: "configure attribute o for top entry using debconf"
  debconf:
    name: slapd
    question: shared/organization
    vtype: string
    value: "{{ ldap_top_organization }}"

- name: "configure purging OpenLDAP database when uninstalling using debconf"
  debconf:
    name: slapd
    question: slapd/purge_database
    vtype: boolean
    value: 'true'

- name: "configure data admin password for OpenLDAP using debconf"
  debconf:
    name: slapd
    question: "{{ item }}"
    vtype: password
    value: "{{ ldap_data_password }}"
  # wrongly reports as changed even when not changed, see https://github.com/ansible/ansible/issues/47676
  changed_when: False
  no_log: True
  loop:
    - slapd/password1
    - slapd/password2

- name: "install software packages"
  apt:
    state: present
    default_release: "{{ ansible_distribution_release }}-backports"
    name:
      - slapd
      - ldap-utils
      - python3-ldap

# libldap-common is a dependency for python-apt so it is already installed in older version
# and thus not upgraded by the previous step
- name: "update libldap-common to latest version"
  apt:
    state: latest
    default_release: "{{ ansible_distribution_release }}-backports"
    name: libldap-common

- name: "make sure the /etc/ldap/ldap.conf file exists (it is part of package libldap-common)"
  template:
    backup: true
    src: ldap.conf.j2
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: '0644'

- name: "install slapd-contrib with Argon2 key derivation function"
  when: ldap_strong_password_hashing
  apt:
    default_release: "{{ ansible_distribution_release }}-backports"
    name: slapd-contrib
    state: present

- name: "hold slapd package from upgrading"
  when: ldap_hold_package
  dpkg_selections:
    name: slapd
    selection: hold

# SHA is used for idempotency, SSHA has different salt each time
- name: "compute config admin password hash"
  command:
    argv: [ 'slappasswd', '-h', '{SHA}', '-s', "{{ ldap_config_password }}" ]
  register: ldap_config_admin_password_hash
  changed_when: False
  no_log: True

- name: "set config admin password"
  ldap_attrs:
    dn: olcDatabase={0}config,cn=config
    attributes:
      olcRootPW: "{{ ldap_config_admin_password_hash.stdout }}"
    state: exact
  no_log: True

- name: "add openldap user to ssl-cert group"
  user:
    name: openldap
    groups: ssl-cert
    append: yes
  register: openldap_ssl_cert_group

- name: "restart OpenLDAP after openldap user added to group ssl-cert"
  service:
    name: slapd
    state: restarted
  when: openldap_ssl_cert_group.changed

- name: "modify LDAP TLS settings"
  ldap_attrs:
    dn: cn=config
    attributes:
      olcTLSCertificateFile: "{{ ldap_certificate_file }}"
      olcTLSCertificateKeyFile: "{{ ldap_certificate_key_file }}"
      olcTLSCACertificateFile: "{{ ldap_certificate_chain_file }}"
    state: exact
  register: ssl_ldif

- name: "enable secure port, plain ldap and local connection"
  lineinfile:
    dest: /etc/default/slapd
    regexp: ^SLAPD_SERVICES=
    line: SLAPD_SERVICES="ldaps:/// ldapi:/// ldap:///"
  register: secure_port_enabled

- name: "restart OpenLDAP after enabling TLS"
  service:
    name: slapd
    state: restarted
  when: secure_port_enabled.changed or ssl_ldif.changed

- name: "pass-through authentication"
  when: ldap_pass_through_authentication
  block:
    - name: "install kerberos and sasl"
      apt:
        name:
          - krb5-user
          - sasl2-bin
        state: present
    - name: "krb5.conf"
      get_url:
        url: https://metavo.metacentrum.cz/krb5.conf
        dest: /etc/krb5.conf
        force: yes
    - name: "saslauthd START=yes"
      lineinfile:
        path: /etc/default/saslauthd
        regexp: 'START='
        line: 'START=yes'
    - name: "saslauthd MECHANISMS=kerberos5"
      lineinfile:
        path: /etc/default/saslauthd
        regexp: 'MECHANISMS='
        line: 'MECHANISMS="kerberos5"'
    - name: "start saslauthd"
      service:
        name: saslauthd
        state: started
    - name: "sasl2 config"
      copy:
        dest: /usr/lib/sasl2/slapd.conf
        content: |
          pwcheck_method: saslauthd
          mech_list: plain login external
      register: sasl_first_pass
    - name: "add user openldap to group sasl"
      user:
        name: openldap
        groups: sasl
        append: yes
    - name: "restart OpenLDAP after enabling SASL"
      service:
        name: slapd
        state: restarted
      when: sasl_first_pass.changed

- name: "OpenLDAP modules"
  block:
    - name: "modules lists"
      set_fact:
        olcModuleLoad_values: [ 'back_mdb' ]
        olcModuleLoad_master_replica: [ 'syncprov', 'accesslog' ]
        olcModuleLoad_memberof: [ 'memberof', 'refint' ]
        olcModuleLoad_sssvlv: [ 'sssvlv' ]
        olcModuleLoad_argon2: [ 'pw-argon2' ]
    - name: "modules for master replica"
      when: ldap_master_replica
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  olcModuleLoad_master_replica }}"
    - name: "modules for memberOf overlay"
      when: ldap_memberOf_overlay
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  olcModuleLoad_memberof }}"
    - name: "module for sssvlv overlay"
      when: ldap_sssvlv_overlay
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  olcModuleLoad_sssvlv }}"
    - name: "module pw-argon2"
      when: ldap_strong_password_hashing
      set_fact:
        olcModuleLoad_values: "{{ olcModuleLoad_values +  olcModuleLoad_argon2 }}"
    - name: "activate modules {{ olcModuleLoad_values }}"
      ldap_attrs:
        dn: cn=module{0},cn=config
        attributes:
          olcModuleLoad: "{{ olcModuleLoad_values }}"
        ordered: yes
        state: present

- name: "set strong hashing method as default for password hashing"
  when: ldap_strong_password_hashing
  ldap_attrs:
    dn: "olcDatabase={-1}frontend,cn=config"
    attributes:
      olcPasswordHash: "{ARGON2}"
    state: exact

- name: "create users"
  include_tasks: user_entry.yml
  loop: "{{ ldap_users }}"
  loop_control:
    loop_var: user_entry

- name: "create replica user"
  when: ldap_master_replica
  include_tasks: user_entry.yml
  vars:
    user_entry:
      user: 'replication'
      password: "{{ ldap_replication_password }}"
      description: "user for LDAP replication"

- name: "LDAP access rules"
  block:
    - name: "LDAP access rules empty"
      set_fact:
        olcAccess_values: []
        oldAccess_replication:
          - >-
            to dn.subtree="{{ ldap_basedn }}"
            by dn.exact="cn=replication,{{ ldap_basedn }}" read
            by * break
    - name: "LDAP access rule for replication must be first"
      when: ldap_master_replica
      set_fact:
        olcAccess_values: "{{ olcAccess_values + oldAccess_replication }}"
    - name: "LDAP access rules start"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + ldap_access_rules_start }}"
    - name: "additional LDAP access rules"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + ldap_access_rules_additional }}"
    - name: "LDAP access rules end"
      set_fact:
        olcAccess_values: "{{ olcAccess_values + ldap_access_rules_end }}"
    - name: "modify OpenLDAP access rights"
      ldap_attrs:
        dn: olcDatabase={1}mdb,cn=config
        attributes:
          olcAccess: "{{ olcAccess_values }}"
        ordered: yes
        state: exact

- name: "set unlimited size of searches"
  ldap_attrs:
    dn: olcDatabase={-1}frontend,cn=config
    attributes:
      olcSizeLimit: "{{ ldap_size_limit }}"
    state: exact

- name: "overlays counter init"
  set_fact:
    overlays_counter: 0

- name: "replication"
  when: ldap_master_replica
  block:
    - name: "no limits for replica"
      ldap_attrs:
        dn: olcDatabase={1}mdb,cn=config
        attributes:
          olcLimits:
            - 'dn.exact="cn=replication,{{ ldap_basedn }}" time=unlimited size=unlimited'
        ordered: yes
        state: exact

    - name: "directory for accesslog"
      file:
        path: /var/lib/ldap/accesslog
        state: directory
        owner: openldap
        group: openldap
        mode: '0755'

    - name: "accesslog database"
      ldap_entry:
        dn: "olcDatabase={2}mdb,cn=config"
        objectClass:
          - olcDatabaseConfig
          - olcMdbConfig
        attributes:
          olcDatabase: '{2}mdb'
          olcDbDirectory: /var/lib/ldap/accesslog
          olcSuffix: cn=accesslog
          olcAccess: '{0}to dn.subtree="cn=accesslog" by dn.exact="cn=replication,{{ ldap_basedn }}" read'
          olcLastMod: 'TRUE'
          olcMaxDerefDepth: 15
          olcReadOnly: 'FALSE'
          olcLimits: 'dn.exact="cn=replication,{{ ldap_basedn }}" time=unlimited size=unlimited'
          olcSizeLimit: unlimited
          olcTimeLimit: unlimited
          olcMonitoring: 'TRUE'
          olcDbCheckpoint: '0 0'
          olcDbIndex:
            - entryCSN eq
            - objectClass eq
            - reqEnd eq
            - reqResult eq
            - reqStart eq
            - reqDN eq
          olcDbMode: '0600'
          olcDbSearchStack: 16
          olcDbMaxsize: 85899345920
        state: present

    - name: "accesslog overlay for main database"
      ldap_entry:
        dn: "olcOverlay={0}accesslog,olcDatabase={1}mdb,cn=config"
        objectClass:
          - olcAccessLogConfig
        attributes:
          olcOverlay: '{0}accesslog'
          olcAccessLogDb: cn=accesslog
          olcAccessLogOps: writes
          olcAccessLogSuccess: 'TRUE'
          olcAccessLogPurge: '2+00:00 1+00:00'
        state: present

    - name: "syncprov overlay for main database"
      ldap_entry:
        dn: "olcOverlay={1}syncprov,olcDatabase={1}mdb,cn=config"
        objectClass:
          - olcSyncProvConfig
        attributes:
          olcOverlay: '{1}syncprov'
          olcSpCheckpoint: '100 10'
        state: present

    - name: "overlays counter +2"
      set_fact:
        overlays_counter: "{{ overlays_counter|int + 2 }}"

    - name: "syncprov overlay for accesslog database"
      ldap_entry:
        dn: "olcOverlay={0}syncprov,olcDatabase={2}mdb,cn=config"
        objectClass:
          - olcSyncProvConfig
        attributes:
          olcOverlay: '{0}syncprov'
          olcSpCheckpoint: '100 10'
          olcSpNoPresent: 'TRUE'
          olcSpReloadHint: 'TRUE'
        state: present


- name: "create ou=People branch"
  when: not ldap_slave_replica
  ldap_entry:
    dn: "ou=People,{{ ldap_basedn }}"
    objectClass: organizationalUnit
    state: present
    bind_dn: "{{ ldap_data_admin_dn }}"
    bind_pw: "{{ ldap_data_password }}"

- name: "replication on slave"
  when: ldap_slave_replica
  ldap_attrs:
    dn: "olcDatabase={1}mdb,cn=config"
    attributes:
      olcSyncrepl: >-
        provider={{ ldap_master_url }}
        type=refreshAndPersist
        rid=0
        retry="5 5 300 +"
        searchbase="{{ ldap_basedn }}"
        attrs="*,+"
        bindmethod=simple
        binddn="cn=replication,{{ ldap_basedn }}"
        credentials={{ ldap_replication_password }}
        logbase="cn=accesslog"
        logfilter="(&(objectClass=auditWriteObject)(reqResult=0))"
        syncdata=accesslog
        tls_cacert=/etc/ssl/certs/ca-certificates.crt
    ordered: yes
    state: exact

# overlays need to have index in their names, but the index depend on their number
- name: "memberOf overlay"
  when: ldap_memberOf_overlay
  ldap_entry:
    dn: "olcOverlay={{ '{' + overlays_counter|string + '}' }}memberof,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - olcMemberOf
      - top
    attributes:
      olcMemberOfRefInt: "TRUE"
    state: present

- name: "overlays counter +1"
  when: ldap_memberOf_overlay
  set_fact:
    overlays_counter: "{{ overlays_counter|int + 1 }}"

- name: "refint overlay"
  when: ldap_memberOf_overlay
  ldap_entry:
    dn: "olcOverlay={{ '{' + overlays_counter|string + '}' }}refint,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - olcRefintConfig
      - top
    attributes:
      olcRefintAttribute: "memberof member manager owner"
    state: present

- name: "overlays counter +1"
  when: ldap_memberOf_overlay
  set_fact:
    overlays_counter: "{{ overlays_counter|int + 1 }}"

- name: "sssvlv overlay"
  when: ldap_sssvlv_overlay
  ldap_entry:
    dn: "olcOverlay={{ '{' + overlays_counter|string + '}' }}sssvlv,olcDatabase={1}mdb,cn=config"
    objectClass:
      - olcConfig
      - olcOverlayConfig
      - top
    state: present

#- name: "overlays counter +1"
#  when: ldap_sssvlv_overlay
#  set_fact:
#    overlays_counter: "{{ overlays_counter|int + 1 }}"

- name: "change the standard schema to allow empty groups"
  when: ldap_allow_empty_groups
  tags: hack
  block:
    - name: "copy core.ldif"
      copy:
        src: etc/ldap/schema/core.ldif
        dest: /etc/ldap/schema/core.ldif
      register: f1
    - name: "copy core.schema"
      copy:
        src: etc/ldap/schema/core.schema
        dest: /etc/ldap/schema/core.schema
      register: f2
    - name: "copy cn={0}core.ldif"
      copy:
        src: 'etc/ldap/slapd.d/cn=config/cn=schema/cn={0}core.ldif'
        dest: '/etc/ldap/slapd.d/cn=config/cn=schema/cn={0}core.ldif'
      register: f3
    - name: "restart slapd"
      when: f1.changed or f2.changed or f3.changed
      service:
        name: slapd
        state: restarted
